[package]
name = "ruga"
version = "0.1.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[[bin]]
name = "ruga"

[dependencies]
piston = "0.16.0"
pistoncore-glutin_window = "0.20.0"
piston2d-graphics = "0.13.0"
piston2d-opengl_graphics = "0.22.0"
piston-viewport = "0.2.0"
rand = "0.3.0"

portaudio = "0.6.0"
sndfile = { git = "https://github.com/thiolliere/rust-sndfile.git" }

#xml-rs = "0.2"
#regex = "0.1"

#piston_window = "0.33.0"
#piston-ai_behavior = "0.11.0"
#piston2d-sprite = "0.20.0"
#image = "0.6.0"
#piston2d-drag_controller = "0.10.0"
#gfx = "0.8.0"
#gfx_device_gl = "0.7.0"
#vecmath = "0.2.0"
#camera_controllers = "0.10.0"
#pistoncore-sdl2_window = "0.22.0"
#rand = "0.3.8"
