[package]
name = "ruga"
version = "0.2.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[[bin]]
name = "ruga"

[dependencies]
graphics = { path = "src/graphics" }
configuration = { path = "src/configuration" }
baal = "*"
#baal = { path = "../baal" }
glium = "*"
specs = "*"
time = "*"
lazy_static = "*"
toml = "*"
rand = "*"
png = "*"

