[package]
name = "ruga"
version = "0.1.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[[bin]]
name = "ruga"

[dependencies]
piston = "0.13.0"
piston-viewport = "0.2.0"
piston2d-graphics = "0.10.0"
pistoncore-glutin_window = "0.16.0"
piston2d-opengl_graphics = "0.15.0"
rand = "0.3"
xml-rs = "0.2"
regex = "0.1"
