[package]
name = "ruga"
version = "0.2.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[[bin]]
name = "ruga"

[dependencies]
thigra = { git = "https://github.com/thiolliere/thigra" }
yaml_unifier = { git = "https://github.com/thiolliere/yaml_unifier" }
yaml-rust = "0.3.0"
baal = "0.2.0"
glium = "0.14.0"
specs = "0.5.0"
hlua = "0.1"
time = "0.1.0"
