[package]
name = "ruga"
version = "0.3.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[[bin]]
name = "ruga"

[dependencies]
clap = "*"
glium = "*"
hlua = "*"
rustyline = "*"
time = "*"
rusttype = "*"
vecmath = "*"
itertools = "*"
unicode-normalization = "*"
arrayvec = "*"
specs = "*"
fnv = "*"
svg = "*"
regex = "*"
