[general]
number_of_thread = 4

[entities]
#groups
char_group          = "00000001"
monster_group       = "00000010"
ball_group          = "00000100"
laser_group         = "00001000"
column_group        = "00010000"
wall_group          = "00100000"

char_mask           = "00110000"
monster_mask        = "00110010"
ball_mask           = "00100000"
laser_mask          = "00000000"
column_mask         = "11111111"
wall_mask           = "11111111"

monster_vision_mask = "00110001"

monster_killer_mask = "00000001"
ball_killer_mask    = "00000011"
laser_killer_mask   = "00000110"

#radius
laser_radius = 0.5
column_radius = 0.5
char_radius = 0.5
wall_radius = 0.5
ball_radius = 0.5
monster_radius = 0.5

#velocities
ball_velocity = 60.0
char_velocity = 10.0
monster_velocity = 10.0

#times to reach almost vmax
char_time = 0.1
monster_time = 1.0
ball_time = 2.0

#weight
ball_weight = 1.0
monster_weight = 1.0
char_weight = 1.0

#color
ball_color = "violet"
laser_color = "yellow"
column_color = "red"
char_color = "blue"
wall_color = "cyan"
monster_color = "magenta"
portal_start_color = "green"
portal_end_color = "orange"

#other
monster_vision_time = 0.5

[physic]
rate = 0.9
unit = 2.0

[levels]
dir = "./levels"
first_level = "toto"

[keys]
up = 25
down = 39
left = 38
right = 40
quit = 9

# [audio]
# check_level = always

# channels = 2
# sample_rate = 44100.
# frames_per_buffer = 64

# effect_dir = "assets/effects"
# music_dir = "assets/musics"

# global_volume = 0.5
# music_volume = 0.8
# effect_volume = 0.3

# distance_model = "pow2"
# distance_model_min = 10
# distance_model_max = 110
# music_loop = true

# effect = []
# music = []

[window]
dimension = [640,480]
vsync = true
multisampling = 4
# fullscreen = false

[camera]
zoom = 0.1

[event_loop]
ups = 120
max_fps = 60

[graphics]
base03 = [ 0.0, 0.16862746, 0.21176471, 1.0 ]
base02 = [ 0.02745098, 0.21176471, 0.25882354, 1.0 ]
base01 = [ 0.34509805, 0.43137255, 0.45882353, 1.0 ]
base00 = [ 0.39607844, 0.48235294, 0.5137255, 1.0 ]
base0 = [ 0.5137255, 0.5803922, 0.5882353, 1.0 ]
base1 = [ 0.5764706, 0.6313726, 0.6313726, 1.0 ]
base2 = [ 0.93333334, 0.9098039, 0.8352941, 1.0 ]
base3 = [ 0.99215686, 0.9647059, 0.8901961, 1.0 ]
yellow = [ 0.70980394, 0.5372549, 0.0, 1.0 ]
orange = [ 0.79607844, 0.29411766, 0.08627451, 1.0 ]
red = [ 0.8627451, 0.19607843, 0.18431373, 1.0 ]
magenta = [ 0.827451, 0.21176471, 0.50980395, 1.0 ]
violet = [ 0.42352942, 0.44313726, 0.76862746, 1.0 ]
blue = [ 0.14901961, 0.54509807, 0.8235294, 1.0 ]
cyan = [ 0.16470589, 0.6313726, 0.59607846, 1.0 ]
green = [ 0.52156866, 0.6, 0.0, 1.0 ]
mode = "dark"
luminosity = 0.5
circle_precision = 32
font_file = "assets/DejaVuSansMono-Bold.ttf"
font_precision = 24
font_ratio = 1.5
