[general]
number_of_thread = 2
persistent_snd_cooldown = 10
difficulty = 1.0

[effect]
color = "base5"
angles = [ 0.7853981633975
         , 2.3561944901925
         , 3.9269908169875
         , 5.4977871437825
         ]
persistance = 0.05
thickness = 0.4
inner_length = 0.5
length = 0.4

[entities]
#groups
char_group          = "00000001"
monster_group       = "00000010"
ball_group          = "00000100"
laser_group         = "00001000"
column_group        = "00010000"
wall_group          = "00100000"

#masks
char_mask           = "00110000"
monster_mask        = "00110010"
ball_mask           = "00100000"
laser_mask          = "00000000"
column_mask         = "11111111"
wall_mask           = "11111111"

monster_vision_mask = "00110001"

monster_killer_mask = "00000001"
ball_killer_mask    = "00000011"
laser_killer_mask   = "00000110"

#sounds
ball_kill_snd = 0
ball_die_snd = 2
laser_kill_snd = 3
char_die_snd = 4
monster_kill_snd = 0
monster_die_snd = 4
portal_snd = 5
column_spawn_snd = 6
ball_vel_snd = 7

laser_persistent_snd = 0
monster_persistent_snd = 1

#radius
laser_radius = 0.5
column_radius = 0.5
char_radius = 0.5
wall_radius = 0.5
ball_radius = 0.5
monster_radius = 0.5

#velocities
ball_velocity = 50.0
char_velocity = 14.0
monster_velocity = 10.0

#times to reach almost vmax
char_time = 0.1
monster_time = 1.0
ball_time = 1.0

#weights
ball_weight = 1.0
monster_weight = 1.0
char_weight = 1.0

#colors
ball_color = "cyan"
laser_color = "violet"
column_color = "base3"
char_color = "red"
wall_color = "base4"
monster_color = "green"
portal_start_color = "base5"
portal_end_color = "base2"
text_color = "base5"

#layers
ball_layer = "middle"
laser_layer = "floor"
column_layer = "ceil"
char_layer = "middle"
wall_layer = "ceil"
monster_layer = "middle"
portal_start_layer = "floor"
portal_end_layer = "floor"

#others
monster_vision_time = 0.2
column_cooldown = 1.0
char_restart = 1.0
ball_vel_snd_coef = 0.01

[menu]
entry_color = "base4"
cursor_color = "red"
background_color = "base1"

clic_snd = 1
background_width = 25.0
background_height = 22.0

[physic]
rate = 0.9
unit = 2.0

[levels]
check_level = "debug"
dir = "levels"
entry_music = "assets/musics/todo.ogg"
corridor_length = 3
hall_length = 1

# colors
empty_col = [0,43,54]
char_col = [220,50,47]
portal_col = [238,232,213]
laser_col = [108,113,196]
monster_col = [133,153,0]
column_col = [88,110,117]
wall_col = [147,161,161]

[keys]
up = [25,111]
down = [39,116]
left = [38,113]
right = [40,114,36]
escape = [9]

[touch]
joystick_rec = [0.0,0.0,10.0,10.0] #TODO
escape_rec = [0.0,0.0,10.0,10.0] #TODO

joystick_radius = 10.0 #TODO

[joystick]
time_to_repeat = 0.1
time_to_start_repeating = 0.5
press_epsilon = 0.5
release_epsilon = 0.01

[audio]
effect_dir = "assets/effects"
music_dir = "."

global_volume = 0.3 # override by save.toml
music_volume = 0.8 # override by save.toml
effect_volume = 0.5 # override by save.toml

distance_model = "pow2"
distance_model_min = 10.0
distance_model_max = 20.0

persistent_effects = ["lights_loop.ogg","monster_persistent.ogg"]

short_effects = [ "null.ogg"
                , "clic.ogg"
                , "destroy_ball.ogg"
                , "laser.ogg"
                , "monster_die.ogg"
                , "portal.ogg"
                , "spawn_ball.ogg"
                , "ball_vel.ogg"
                ]

transition_type = "smooth"
transition_time = 2000

[window]
vsync = true
multisampling = 2
fullscreen = false
fullscreen_on_primary_monitor = true
fullscreen_monitor = 0 # if not fullscreen_on_primary_monitor
dimension = [640,480] # if not fullscreen

[camera]
zoom = 0.08

[event_loop]
ups = 60
max_fps = 60

[graphics]
base03  = [ 0.00000000, 0.16862746, 0.21176471, 1.0 ]
base02  = [ 0.02745098, 0.21176471, 0.25882354, 1.0 ]
base01  = [ 0.34509805, 0.43137255, 0.45882353, 1.0 ]
base00  = [ 0.39607844, 0.48235294, 0.51372550, 1.0 ]
base0   = [ 0.51372550, 0.58039220, 0.58823530, 1.0 ]
base1   = [ 0.57647060, 0.63137260, 0.63137260, 1.0 ]
base2   = [ 0.93333334, 0.90980390, 0.83529410, 1.0 ]
base3   = [ 0.99215686, 0.96470590, 0.89019610, 1.0 ]
yellow  = [ 0.70980394, 0.53725490, 0.00000000, 1.0 ]
orange  = [ 0.79607844, 0.29411766, 0.08627451, 1.0 ]
red     = [ 0.86274510, 0.19607843, 0.18431373, 1.0 ]
magenta = [ 0.82745100, 0.21176471, 0.50980395, 1.0 ]
violet  = [ 0.42352942, 0.44313726, 0.76862746, 1.0 ]
blue    = [ 0.14901961, 0.54509807, 0.82352940, 1.0 ]
cyan    = [ 0.16470589, 0.63137260, 0.59607846, 1.0 ]
green   = [ 0.52156866, 0.60000000, 0.00000000, 1.0 ]

mode = "dark" # override by save.toml
luminosity = 1.0 # override by save.toml
circle_precision = 64
font_file = "assets/fonts/DejaVuSansMono-Bold.ttf"
billboard_font_scale = 0.04
font_scale = 0.4

[text]
top = 4
bottom = -5
right = 16
left = -11
