language: rust

rust:
 - stable
 - nightly

addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev

after_success:
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo doc &&
        sudo pip install ghp-import &&
        ghp-import target/doc &&
        git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN}
