music = "main.ogg"

[[dungeons]]
name = "Test"
music = "main.ogg"
rooms = ["map_1.png"]

[[dungeons]]
name = "Nerval"
music = "main.ogg"
rooms = ["nerval_1.txt","nerval_2.txt","nerval_3.txt","nerval_4.txt"]

[[dungeons]]
name = "Random map"
music = "main.ogg"
rooms = ["map_1.png","map_2.png","map_3.png","map_4.png"]
