music = "main.ogg"

[[dungeons]]
name = "Test"
music = "main.ogg"
rooms = ["map_1.png"]

[[dungeons]]
name = "Nerval"
music = "main.ogg"
rooms = ["nerval_1.txt","nerval_2.txt","nerval_3.txt","nerval_4.txt"]
