music = "main.ogg"

[[dungeons]]
name = "Nerval"
music = "main.ogg"
rooms = ["nerval_1.txt","nerval_2.txt","nerval_3.txt","nerval_4.txt"]

[[dungeons]]
name = "second"
music = "main.ogg"
rooms = ["sound.png","main.png"]
[[dungeons]]
name = "second"
music = "main.ogg"
rooms = ["main.png","main.png"]
