music = "main.ogg"

[[dungeons]]
name = "test"
music = "main.ogg"
rooms = ["entry.png"]

[[dungeons]]
name = "Nerval"
music = "main.ogg"
rooms = ["nerval_1.txt","nerval_2.txt","nerval_3.txt","nerval_4.txt"]

[[dungeons]]
name = "some"
music = "main.ogg"
rooms = ["main.png","sound.png"]
