---
graphics: external file

audio:
    check_level: always

    channels: 2
    sample_rate: 44100.
    frames_per_buffer: 64

    effect_dir: assets/effects
    music_dir: assets/musics

    global_volume: 0.5
    music_volume: 0.8
    effect_volume: 0.3

    distance_model: [pow2,10.,110.]
    music_loop: true

    effect:
    music:

window:
    dimension: [640,480]
    vsync: true
    multisampling: 0
    fullscreen: false

event_loop:
    ups: 120
    max_fps: 60
camera:
    zoom: 0.1
...
