[package]
name = "graphics"
version = "0.1.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[dependencies]
glium = "*"
vecmath = "*"
rusttype = "*"
unicode-normalization = "*"
itertools = "*"
arrayvec = "*"
serde = "1.0"
serde_derive = "1.0"
