[package]
name = "graphics"
version = "0.1.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[dependencies]
glium = "*"
vecmath = "*"
toml = "*"
glium_text = { path = "src/glium_text" }
configuration = { path = "../configuration" }
